name: "🐛 Bug Report"
description: "Help us fix issues by providing a detailed report."
body:
  - type: checkboxes
    id: guidelines
    attributes:
      label: "Guidelines"
      description: "Please search for already reported issues to avoid submitting a duplicate. [Search existing issues](https://github.com/mollyim/mollyim-android/issues?q=is%3Aissue+-label%3Afeature-request)."
      options:
        - label: "Yes, I have searched for existing issues"
          required: true
  - type: textarea
    id: description-of-bug
    attributes:
      label: "Bug Description"
      description: "Explain the problem clearly, including steps to reproduce."
      placeholder: "What did you do, and what went wrong?"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "How to take screenshots: https://support.google.com/android/answer/9075928"
      placeholder: "Drag and drop images or videos here."
    validations:
      required: false
  - type: input
    id: device-model
    attributes:
      label: "Device Model"
      description: "Found in Settings ► About Phone."
      placeholder: "e.g. Pixel 9"
    validations:
      required: false
  - type: input
    id: android-version
    attributes:
      label: "Android Version"
      description: "Found in Settings ► About Phone."
      placeholder: "e.g. Android 14"
    validations:
      required: false
  - type: input
    id: app-version
    attributes:
      label: "App Version"
      description: "Found in Molly's Settings ► Help"
      placeholder: "e.g. v7.21.5-2"
    validations:
      required: false
  - type: input
    id: debug-log
    attributes:
      label: "Link to Debug Log"
      description: |
        If possible, include a debug log via Molly’s Settings ► Help ► Debug Log. Copy the URL here.
        Logs cover ~24 hours, so capture it soon after encountering the bug.
      placeholder: "e.g. https://debuglogs.org/..."
    validations:
      required: false
